apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: compliance-operator
  namespace: openshift-marketplace
spec:
  displayName: Compliance Operator
  publisher: github.com/openshift/compliance-operator
  sourceType: grpc
  image: quay.io/gquillar/compliance-operator-index:latest
